import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'remixicon/fonts/remixicon.css'
import { StaticImageData } from 'next/image'
import icon from './assets/icons/favicon-32x32.png'
import { Analytics } from '@vercel/analytics/react'

const inter = Inter({ subsets: ['latin'] })

export interface icon {
  src: String | StaticImageData
}

export const metadata: Metadata = {
  title: 'Efje | Portofolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head>
        <meta
          name='viewport'
          content='width=device-width; initial-scale=1.0'
        ></meta>
        <link rel='shortcut icon' href={icon.src} type='image/x-icon' />
      </head>
      <body className={inter.className}>
        {children}
        <Analytics />
      </body>
    </html>
  )
}
